apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    editable: true
    uid: victoriametrics
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
    secureJsonData: {}